spring.application.name=demo
# --- GeoApi ---
geoapi.base-url=https://apiv1.geoapi.es
geoapi.api-key=5d5086f62a1b1e75748642f4e717f0217de404f716f56fb82341e77e9cb0f912


# DATABASE
spring.datasource.url=jdbc:mysql://mysql:3306/Proyecto_ruta?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.initializationFailTimeout=60000

#LOG
#logging.level.org.springframework.security=DEBUG

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# EMAIL
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=aad5fc001@smtp-brevo.com
spring.mail.password=${SPRING_MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000