spring.application.name=demo
# --- GeoApi ---
geoapi.base-url=https://apiv1.geoapi.es
geoapi.api-key=5d5086f62a1b1e75748642f4e717f0217de404f716f56fb82341e77e9cb0f912


# DATABASE
spring.datasource.url=jdbc:mysql://mysql:3306/Proyecto_ruta?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.initializationFailTimeout=60000

#LOG
#logging.level.org.springframework.security=DEBUG

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# EMAIL - CONFIGURACIÓN TOTAL SSL
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=ryeste124@gmail.com
spring.mail.password=wbmpyudqegptarkv22

# Forzar el uso de SSL para evitar que busque el puerto 587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.starttls.enable=false

# Socket Factory (Esto es lo que suele faltar para que el 465 funcione en Java)
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.socketFactory.fallback=false

# Tiempos de espera
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000